version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ${HEROKU_PG_HOST}
            database: ${HEROKU_PG_DATABASE}
            schema: public
            user: ${HEROKU_PG_USER}
            password: ${HEROKU_PG_PASSWORD}
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
